### ISSUE TITLE
error on /controlpanel URL

### ISSUE THREAD

**Issue by tyrcho** [rchatley/extreme_startup#40]
When I access /controlpanel, I get this ruby exception :

NoMethodError at /controlpanel
undefined method `round' for #<ExtremeStartup::WarmupQuestionFactory:0x0000000154dd40>

Other URLs seem to work fine.

I'm running in docker, here is my env 

HOSTNAME=3a3e170a5bc1
GEM_HOME=/usr/local/bundle
TERM=xterm
BUNDLE_APP_CONFIG=/usr/local/bundle
PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WARMUP=0
PWD=/usr/src/app
RUBY_MAJOR=1.9
SHLVL=1
HOME=/root
RUBY_VERSION=1.9.3-p551
_=/usr/bin/env

**Comment by rchatley** [comment]
Oh, yes, the /controlpanel url doesn't work in the warmup round. If you
don't set WARMUP at all then you should get the real QuestionFactory, and
/controlpanel should work.

We should probably make it so it doesn't throw an error if you do that
though...

--Robert

**Comment by tyrcho** [comment]
Thanks, without WARMUP it works well :)
