### ISSUE TITLE
ruby not found in docker

### ISSUE THREAD

**Issue by tyrcho** [rchatley/extreme_startup#41]
When I run the container like that ```docker@boot2docker:/mnt/sda2/tmp/extreme_startup$ docker run -ti -p 80:3000 es``` I get this error : ```/bin/sh: 1: [ruby: not found```

When I run it with 

     docker run -ti -p 80:3000 es bash
     ruby web_server.rb

It works

**Comment by jonashackt** [comment]
Got the same error... With the trailing bash it works tho

**Comment by rchatley** [comment]
@tclavier @wadouk @mostalive can anyone help here? I haven't looked at any of the Docker stuff.

**Comment by tyrcho** [comment]
@rchatley please have a look at PR #43 I think it solves nicely this issue.
